import type { Metadata } from "next";
import "@cloudscape-design/global-styles/index.css";
import { Navigation } from "@/app/Navigation";

export const metadata: Metadata = {
  title: "Contact Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
      </body>
    </html>
  );
}
